### ISSUE TITLE
Sym report a 404 error

### ISSUE THREAD

**Issue by arnaudgst** [pyrogenic/elephant#4]
Sym report a 404 error (https://github.com/pyrogenic/sym)

**Comment by pyrogenic** [comment]
Yes, unfortunately, the synthetic monorepo isn't yet public. I'll see what I can do about that. Were you able to try out the [deployed version](https://pyrogenic.github.io/elephant/)?

**Comment by pyrogenic** [comment]
I've made pyrogenic/sym public — you should be able to access it now. Let me know how it goes!
